//! Embeds the built Figma plugin (`manifest.json`, `dist/code.js`,
//! `dist/ui.html`) into the daemon binary, so a Homebrew-installed daemon can
//! write the plugin files out to disk (`turbofig setup`, a later command)
//! with no separate download and no copy of the repo.
//!
//! The plugin is a Bun/TypeScript build (`cd plugin && bun run build`), not
//! a Cargo artifact, so a Rust-only contributor (and the CI Rust job, which
//! never runs Bun) must still be able to `cargo build`. When `plugin/dist` is
//! missing, this script emits a `cargo:warning` and generates a stub that
//! makes `embedded::embedded_plugin()` return `None`, instead of failing the
//! build.

use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let plugin_dir = manifest_dir.join("../plugin");
    let manifest_path = plugin_dir.join("manifest.json");
    let code_path = plugin_dir.join("dist/code.js");
    let ui_path = plugin_dir.join("dist/ui.html");

    // Rebuild whenever any embedded source file changes, and whenever the
    // plugin is built for the first time (dist/ created where it did not
    // exist before).
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    println!("cargo:rerun-if-changed={}", code_path.display());
    println!("cargo:rerun-if-changed={}", ui_path.display());

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let dest = out_dir.join("embedded_plugin_data.rs");

    if manifest_path.exists() && code_path.exists() && ui_path.exists() {
        write_embedded_source(&dest, &manifest_path, &code_path, &ui_path);
    } else {
        println!(
            "cargo:warning=turbofig: plugin/dist not found; building without an embedded plugin. \
             Run `cd plugin && bun run build` first to embed it (needed for `turbofig setup`)."
        );
        write_stub_source(&dest);
    }
}

/// Writes generated Rust source that embeds the three plugin files via
/// `include_str!` with absolute paths, so it works regardless of the
/// generated file's own location under `OUT_DIR`.
fn write_embedded_source(dest: &Path, manifest: &Path, code: &Path, ui: &Path) {
    let src = format!(
        r#"// Generated by build.rs. Do not edit.
pub(crate) fn raw_embedded_plugin() -> Option<(&'static str, &'static str, &'static str)> {{
    Some((
        include_str!({manifest:?}),
        include_str!({code:?}),
        include_str!({ui:?}),
    ))
}}
"#,
        manifest = manifest
            .canonicalize()
            .unwrap_or_else(|_| manifest.to_path_buf()),
        code = code.canonicalize().unwrap_or_else(|_| code.to_path_buf()),
        ui = ui.canonicalize().unwrap_or_else(|_| ui.to_path_buf()),
    );
    std::fs::write(dest, src).expect("write generated embedded_plugin_data.rs");
}

/// Writes a stub that makes `embedded_plugin()` return `None`.
fn write_stub_source(dest: &Path) {
    let src = "// Generated by build.rs. Do not edit.\n\
pub(crate) fn raw_embedded_plugin() -> Option<(&'static str, &'static str, &'static str)> {\n    None\n}\n";
    std::fs::write(dest, src).expect("write stub embedded_plugin_data.rs");
}
