//! Embeds the built Figma plugin (`manifest.json`, `dist/code.js`,
//! `dist/ui.html`) into the daemon binary, so a Homebrew-installed daemon can
//! write the plugin files out to disk (`turbofig setup`, a later command)
//! with no separate download and no copy of the repo.
//!
//! The plugin is a Bun/TypeScript build (`cd plugin && bun run build`), not
//! a Cargo artifact, so a Rust-only contributor (and the CI Rust job, which
//! never runs Bun) must still be able to `cargo build`. When `plugin/dist` is
//! missing, this script emits a `cargo:warning` and generates a stub that
//! makes `embedded::embedded_plugin()` return `None`, instead of failing the
//! build.

use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let plugin_dir = manifest_dir.join("../plugin");
    let manifest_path = plugin_dir.join("manifest.json");
    let code_path = plugin_dir.join("dist/code.js");
    let ui_path = plugin_dir.join("dist/ui.html");

    // Rebuild whenever any embedded source file changes, and whenever the
    // plugin is built for the first time (dist/ created where it did not
    // exist before).
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    println!("cargo:rerun-if-changed={}", code_path.display());
    println!("cargo:rerun-if-changed={}", ui_path.display());

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let dest = out_dir.join("embedded_plugin_data.rs");

    if manifest_path.exists() && code_path.exists() && ui_path.exists() {
        let normalized_ui_path = out_dir.join("embedded_ui_normalized.html");
        normalize_ui_html_file(&ui_path, &normalized_ui_path);
        write_embedded_source(&dest, &manifest_path, &code_path, &normalized_ui_path);
    } else {
        println!(
            "cargo:warning=turbofig: plugin/dist not found; building without an embedded plugin. \
             Run `cd plugin && bun run build` first to embed it (needed for `turbofig setup`)."
        );
        write_stub_source(&dest);
    }
}

/// Writes generated Rust source that embeds the three plugin files via
/// `include_str!` with absolute paths, so it works regardless of the
/// generated file's own location under `OUT_DIR`.
fn write_embedded_source(dest: &Path, manifest: &Path, code: &Path, ui: &Path) {
    let src = format!(
        r#"// Generated by build.rs. Do not edit.
pub(crate) fn raw_embedded_plugin() -> Option<(&'static str, &'static str, &'static str)> {{
    Some((
        include_str!({manifest:?}),
        include_str!({code:?}),
        include_str!({ui:?}),
    ))
}}
"#,
        manifest = manifest
            .canonicalize()
            .unwrap_or_else(|_| manifest.to_path_buf()),
        code = code.canonicalize().unwrap_or_else(|_| code.to_path_buf()),
        ui = ui.canonicalize().unwrap_or_else(|_| ui.to_path_buf()),
    );
    std::fs::write(dest, src).expect("write generated embedded_plugin_data.rs");
}

/// Stable markers `plugin/build-ui.ts` wraps around the pairing-token
/// literal in the bundled UI output. See that file's design note.
const TOKEN_MARKER_START: &str = "/*TURBOFIG_TOKEN_START*/";
const TOKEN_MARKER_END: &str = "/*TURBOFIG_TOKEN_END*/";

/// The placeholder literal (JS string, quotes included) that must always sit
/// between the markers in the embedded copy. Must match the quoted form
/// `plugin/build-ui.ts` emits via `JSON.stringify("__TURBOFIG_PAIRING_TOKEN__")`.
const PLACEHOLDER_LITERAL: &str = "\"__TURBOFIG_PAIRING_TOKEN__\"";

/// Reads `ui_path` (a local `dist/ui.html`, which may embed a real pairing
/// token read from a contributor's own `~/.turbofig/token`; see
/// `plugin/build-ui.ts`'s `readLocalToken`), forces whatever sits between
/// the stable token markers back to the placeholder, and writes the result
/// to `normalized_path`. The embedded daemon binary must never carry a real
/// token: `write_plugin_files` replaces the placeholder with the real token
/// at install time, and it cannot do that if the placeholder is already gone.
fn normalize_ui_html_file(ui_path: &Path, normalized_path: &Path) {
    let contents = std::fs::read_to_string(ui_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", ui_path.display()));
    let normalized = normalize_ui_html(&contents);
    std::fs::write(normalized_path, normalized)
        .unwrap_or_else(|e| panic!("write {}: {e}", normalized_path.display()));
}

/// Pure text transform: finds every `TOKEN_MARKER_START`/`_END` pair and
/// replaces everything between each pair with `PLACEHOLDER_LITERAL`. Panics
/// (failing the build) if no pair is found, or if the result does not carry
/// `PLACEHOLDER_LITERAL` at least once afterward: either way a real token
/// could end up embedded in the binary verbatim, and `write_plugin_files`
/// would have no placeholder left to inject the real token into. Rebuild the
/// plugin (`cd plugin && bun run build`) to regenerate `dist/ui.html` with
/// the markers the current `build-ui.ts` writes.
fn normalize_ui_html(contents: &str) -> String {
    let mut out = String::with_capacity(contents.len());
    let mut rest = contents;
    let mut pairs_replaced = 0u32;

    loop {
        match (rest.find(TOKEN_MARKER_START), rest.find(TOKEN_MARKER_END)) {
            (Some(start), Some(end)) if end > start => {
                let inner_start = start + TOKEN_MARKER_START.len();
                out.push_str(&rest[..inner_start]);
                out.push_str(PLACEHOLDER_LITERAL);
                out.push_str(&rest[end..end + TOKEN_MARKER_END.len()]);
                rest = &rest[end + TOKEN_MARKER_END.len()..];
                pairs_replaced += 1;
            }
            _ => {
                out.push_str(rest);
                break;
            }
        }
    }

    if pairs_replaced == 0 || !out.contains(PLACEHOLDER_LITERAL) {
        panic!(
            "turbofig: dist/ui.html has no pairing-token markers; it may embed a real token \
             verbatim. Run `cd plugin && bun run build` to regenerate it with the markers the \
             current build-ui.ts writes."
        );
    }

    out
}

/// Writes a stub that makes `embedded_plugin()` return `None`.
fn write_stub_source(dest: &Path) {
    let src = "// Generated by build.rs. Do not edit.\n\
pub(crate) fn raw_embedded_plugin() -> Option<(&'static str, &'static str, &'static str)> {\n    None\n}\n";
    std::fs::write(dest, src).expect("write stub embedded_plugin_data.rs");
}
